django_google_maps/urls.py
from django.urls import include, path
from django.contrib import admin

from map import urls as map_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(map_urls)),
]

map/urls.py
from django.urls import include, path
from django.views.generic import TemplateView
from rest_framework import routers

from map import views as map_views


router = routers.DefaultRouter()
router.register(r'searches', map_views.SearchViewSet, basename='searches')


urlpatterns = [
    path('', TemplateView.as_view(template_name="map/map.html")),
    path('api/v1/', include(router.urls)),
    path('api/v1/yelp/search/', map_views.YelpView.as_view()),
]

map/models.py
import django.contrib.gis.db.models as gis_models
from django.db import models


class Search(models.Model):
    term = models.CharField(max_length=255, null=True, blank=True)
    position = gis_models.PointField(srid=4326, dim=2)
    results_count = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} ({})".format(self.term, self.position)

map/views.py
from django.conf import settings
from django.contrib.gis.geos import Point
from django.http import JsonResponse
from rest_framework import permissions, viewsets
from rest_framework.views import APIView
from yelpapi import YelpAPI

from map import models as map_models
from map import serializers as map_serializers


class SearchViewSet(viewsets.ModelViewSet):
    serializer_class = map_serializers.SearchSerializer
    queryset = map_models.Search.objects.all()


class YelpView(APIView):
    permission_classes = (permissions.AllowAny,)

    def get(self, request, *args, **kwargs):
        yelp_api = YelpAPI(settings.YELP_API_KEY)

        search_results = yelp_api.search_query(**self.request.GET)

        term = request.GET.get('term')
        longitude = float(request.GET.get('longitude'))
        latitude = float(request.GET.get('latitude'))
        results_count = search_results['total']
        map_models.Search.objects.create(term=term,
                                         position=Point(longitude, latitude),
                                         results_count=results_count)

        return JsonResponse(search_results)

django_google_maps/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css" media="screen">

  <title>{% block title %}{% endblock %}</title>

  {% block extra_head %}{% endblock %}
</head>
<body>

<div class="content">
  {% block content %}{% endblock %}
</div>

{% block footer %}
  <div class="footer">
    <div class="center">
      <div>
        <span class="mobile_hidden">
          <a target="_blank" href="https://github.com/jessamynsmith/django-google-maps">Source code</a> here.
            <br>
            Like my work? Tip me! <a target="_blank" href="https://www.paypal.me/jessamynsmith">https://www.paypal.me/jessamynsmith</a>
        </span>
      </div>
    </div>
  </div>
{% endblock %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.1.4/js.cookie.min.js"></script>

{% block extra_js %}{% endblock %}

</body>
</html>

map/templates/map/map.html
{% extends 'base.html' %}

{% load static %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static 'map/css/map.css' %}" type="text/css">
{% endblock extra_head %}

{% block content %}

    <h2 class="center">Example Map</h2>

    <form id="id_search_form">
        <input type="text" id="id_term" name="term" placeholder="Enter a search term"/>
        <input type="submit" value="Search">
    </form>

    <div id="map">
        <h3 id="geolocation">Geolocating...</h3>
    </div>

{% endblock content %}

{% block extra_js %}

    <!-- Must be before google maps include, as it contains initMap -->
    <script type="text/javascript" src="{% static 'map/js/map.js' %}"></script>

    <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_MAPS_API_KEY }}&callback=initMap"></script>

{% endblock extra_js %}